options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # build
  - name: 'gcr.io/cloud-builders/docker' #image prebuild oleh google
    args: ['build', '-t', 'gcr.io/southern-field-441210-n4/fastapi-app:latest', '.']

    # push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/southern-field-441210-n4/fastapi-app:latest']

  # deploy to cloud run
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #  entrypoint: gcloud
  #  args: ['run', 'deploy', 'fast-api-test', '--image', 'gcr.io/southern-field-441210-n4/fastapi-app:latest','--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated'] #

  # authenticate to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ci-cd-cluster --zone us-west1-a --project southern-field-441210-n4

  # deploy to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml

images:
  - 'gcr.io/southern-field-441210-n4/fastapi-app:latest'